faq/urls.py
"""
This file contains the url paths for the faq app
"""


from django.urls import path

from faq import views

urlpatterns = [
    path(r'landing/', views.landing, name="landing"),
    path(r'memo_list/', views.memo_list, name="memo_list"),
    path(r'answer_search/', views.answer_search, name="answer_search"),
    path(r'answer_detail/<int:answer_id>', views.answer_detail, name="answer_detail"),
    path(r'answer_validate/', views.answer_validate, name="answer_validate"),
    path(r'question_ask/', views.question_ask, name="question_ask"),
    path(r'ml_info/', views.ml_info, name="ml_info"),
    ]

recipes/urls.py
"""
This file contains the url paths for the recipes app
"""

from django.urls import path

from recipes import views

urlpatterns = [
    path(r'landing/', views.landing, name="landing"),
    path(r'recipe_download/<int:recipe_id>',
         views.recipe_download,
         name="recipe_download"
    ),
    path(r'recipe_refresh/', views.recipe_refresh, name="recipe_refresh"),
    path(r'grocery_list/', views.grocery_list, name="grocery_list")
    ]

stradacore/urls.py
"""stradacore URL Configuration
contains the path for faq and recipes apps, admin,
and ckeditor library uploader
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

from faq import views

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
    path('faq/', include(('faq.urls', 'faq'), namespace="faq")),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace="recipes")),
    path('videos/', include(('videos.urls', 'videos'), namespace="videos")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
"""
recipes/models.py contains the Recipe, Ingredient and IngredientType models.
It also describes the RecipeIngredient association table.
"""
from random import sample

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from fpdf import FPDF

from django.conf import settings


class RecipeManager(models.Manager):
    # Contains the sort_recipes_ingredients() method
    def sort_recipe_ingredients(self, str_array):
        """
        Takes an array of recipe names and returns a dictionary containing
        the ingredients of these recipes (RecipeIngredient objects)
        sorted by ingredient type
        """
        ri_list = []
        for name in str_array:
            recipe = self.get(name=name)
            ri_list.extend(recipe.recipeingredient_set.all())

        sections = {}

        for it in IngredientType.objects.all():
            sections[it.name] = []

        for ri in ri_list:
            sections[ri.ingredient.type.name].append(ri)

        return sections

    def get_remaining_recipes(self, type, ids):
        # Returns all recipes of a given type whose id is not in a list of ids
        same_type_recipes = [recipe.id for recipe in self.filter(type=type)]
        remaining_recipes = list(set(same_type_recipes) - set(ids))
        if remaining_recipes:
            selected_recipe = Recipe.objects.get(
                pk=sample(remaining_recipes, 1)[0])
            return selected_recipe
        else:
            return None

    def stringify_recipe_ingredients(self, recipe):
        """
        Takes a recipe and returns an array of strings describing its
        ingredients with their quantity and unit
        """
        ingredient_list = []
        for ri in recipe.recipeingredient_set.all():
            if ri.quantity:
                ingredient_list.append(
                    "{0} : {1} {2}".format(ri.ingredient.name,
                                           '{0:g}'.format(ri.quantity),
                                           ri.unit
                                           )
                )
            else:
                ingredient_list.append(ri.ingredient.name)

        return ingredient_list

    def max_meal_number(self, absolute_max):
        """
        Returns the lowest number between absolute_max and the number of
        matching recipes for each ingredient type
        """
        max_meal_number = min(
            len(self.filter(type="F")),
            len(self.filter(type="M")),
            len(self.filter(type="D")),
            absolute_max
        )
        return max_meal_number


class RecipeIngredientManager(models.Manager):
    # Contains the aggregate_recipe_ingredients() method
    def aggregate_recipe_ingredients(self, dic):
        """
        Takes a dict where each key is an ingredient type and returns an array
        of RecipeIngredient objects. Returns a dict with similar structure,
        except the arrays contains readable string versions of the recipe
        ingredients. Duplicate ingredients are merged if their unit permits it.
        """
        aggregated_ingredients = {}
        for count, section in enumerate(dic.values()):
            section_ingredients = set([ri.ingredient.name for ri in section])
            section_grocery = []
            for name in section_ingredients:
                matching_ris = [ri for ri in section
                                if ri.ingredient.name == name]
                matching_quantities = [ri.quantity for ri in matching_ris]
                matching_units = [ri.unit for ri in matching_ris]
                if matching_quantities == [None]:
                    section_grocery.append(name)

                elif {"cl", "g", ""} & set(matching_units) == set():
                    section_grocery.append(name)

                else:
                    for unit in ["cl", "g", ""]:
                        if unit in matching_units:
                            quant = sum([ri.quantity for ri in matching_ris
                                      if (ri.unit == unit and ri.quantity)])
                            section_grocery.append(
                                "{0:g}{1} {2}".format(quant, unit, name)
                            )

            aggregated_ingredients[[*dic][count]] = section_grocery

        return aggregated_ingredients


class PDFManager(models.Manager):
    # Contains the create_pdf() method, used to generate grocery list
    def create_pdf(self, dic):
        """
        Takes a dictionnary with arrays of strings as values, creates a pdf out
        of it, then saves and returns the file
        """
        pdf_list = FPDF()
        pdf_list.add_page()
        for key in dic.keys():
            if dic[key]:
                pdf_list.set_font("Arial", size=16)
                pdf_list.cell(200, 15, txt=key, ln=1, align="L")
                pdf_list.set_font("Arial", size=12)
                for grocery in dic[key]:
                    pdf_list.cell(200, 10, txt=grocery, ln=1, align="L")
        path = settings.MEDIA_ROOT + "/grocery.pdf"
        pdf_list.output(path)
        self.all().delete()
        holder = self.create(pdf_file="grocery.pdf")
        file = holder.pdf_file
        return file


class IngredientType(models.Model):
    """
    A simple string to name an ingredient category,
    later referenced in the Ingredient model
    """
    name = models.TextField("type", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "type d'ingrédient"
        verbose_name_plural = "types d'ingrédient"


class Ingredient(models.Model):
    """
    The Ingredient model stores a name, unit and type as an ingredient
    usable in the Recipe model
    """
    name = models.CharField(
        "Nom de l'ingrédient",
        max_length=50,
        unique=True
    )
    type = models.ForeignKey(IngredientType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "ingrédient"
        verbose_name_plural = "ingrédients"


class Recipe(models.Model):
    """
    The Recipe model is key to the recipes app core feature.
    It contains the name (string), directions (ckeditor upload field) and type
    (one among three choices) and ingredients (through the RecipeIngredient
    custom association table) of a recipe.
    """
    FIRST_COURSE = "F"
    MAIN_COURSE = "M"
    DESSERT = "D"
    RECIPE_TYPE_CHOICES = [
        (FIRST_COURSE, 'Entrée'),
        (MAIN_COURSE, 'Plat principal'),
        (DESSERT, 'Dessert'),
    ]
    name = models.CharField(
        "Nom de la recette",
        max_length=100,
        unique=True
    )
    directions = RichTextUploadingField("Instructions", blank=True)
    type = models.CharField(
        max_length=1,
        choices=RECIPE_TYPE_CHOICES,
        default=MAIN_COURSE,
    )
    ingredients = models.ManyToManyField(Ingredient,
                                         through="RecipeIngredient")
    pdf_file = models.FileField("Fichier PDF",
                                upload_to="recipes_pdfs/",
                                blank=True
                                )
    objects = RecipeManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "recette"
        verbose_name_plural = "recettes"


class RecipeIngredient(models.Model):
    """
    This model is a custom association table between Recipe and Ingredient,
    that allows to store a specific quantity for each single association
    """
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField("Quantité", blank=True, null=True)
    unit = models.CharField("Unité (facultatif)", max_length=30, blank=True)
    objects = RecipeIngredientManager()

    class Meta:
        verbose_name = "association ingrédients-recettes"
        verbose_name_plural = "associations ingrédients-recettes"


class PDFHolder(models.Model):
    # Simply stores a pdf file about to be downloaded
    pdf_file = models.FileField("Fichier PDF",
                                upload_to="test/",
                                blank=True
                                )
    objects = PDFManager()

recipes/forms.py
"""
Contains the recipes app's forms, such as the recipe search form,
used by the users to find meals and recipes matching their own criteria
"""

from django import forms

from recipes.models import Recipe


class RecipeSearchForm(forms.Form):
    """
    The recipe search form is used in the recipes app main feature.
    It must contain a number of meal to produce (maximum possible, up to 7),
    and between one and three course options
    """
    max_meal_number = Recipe.objects.max_meal_number(7)
    _meal_choices = [(x, x) for x in range(1, max_meal_number+1)]
    _course_choices = (
        ("F", "Entrée"),
        ("M", "Plat Principal"),
        ("D", "Dessert"),
    )
    meal_number = forms.ChoiceField(choices=_meal_choices)
    course_options = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=_course_choices
    )

recipes/views.py
"""
The views of the recipes app handle the recipe search engine and the
creation of groceries list.
"""
from random import sample

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

from recipes.forms import RecipeSearchForm
from recipes.models import Recipe, PDFHolder, RecipeIngredient


def landing(request):
    """
    The landing view displays the home page and search form for the recipes
    app when accessed through GET.
    When using POST through the search form, the view also displays the search
    results.
    """

    context = {
        'form': RecipeSearchForm()
    }

    if request.method == 'POST':
        form = RecipeSearchForm(request.POST)
        if form.is_valid():
            meal_number = int(form.cleaned_data['meal_number'])
            if "F" in form.cleaned_data['course_options']:
                fcs = sample(list(Recipe.objects.filter(type="F")),
                             meal_number)
            if "M" in form.cleaned_data['course_options']:
                mcs = sample(list(Recipe.objects.filter(type="M")),
                             meal_number)
            if "D" in form.cleaned_data['course_options']:
                dts = sample(list(Recipe.objects.filter(type="D")),
                             meal_number)

            meal_list = []
            for x in range(0, meal_number):
                meal = []
                if "fcs" in locals(): meal.append(fcs[x])
                if "mcs" in locals(): meal.append(mcs[x])
                if "dts" in locals(): meal.append(dts[x])
                meal_list.append(meal)

            context["meal_list"] = meal_list

    return render(request, 'recipes/recipes_landing.html', context)


def recipe_download(request, recipe_id):
    # AJAX downloads a recipe's pdf file
    if Recipe.objects.get(id=recipe_id).pdf_file:
        pdf_file = Recipe.objects.get(id=recipe_id).pdf_file
        response = HttpResponse(pdf_file, content_type='text/plain')

        return response


def recipe_refresh(request):
    """
    AJAX sends data about a random recipe of a given type, selected from those
    that has not yet been displayed on the page that sent the request
    """
    if request.method == "POST":
        type = request.POST.get("recipe_type")
        ids = request.POST.get("recipe_ids")
        id_array = (int(n) for n in ids.split())
        remaining_recipe = Recipe.objects.get_remaining_recipes(type, id_array)

        if not remaining_recipe:
            data = {"status": "out"}
            return JsonResponse(data)

        str_list = Recipe.objects.stringify_recipe_ingredients(remaining_recipe)

        data = {
            "status": "ok",
            "id": remaining_recipe.id,
            "name": remaining_recipe.name,
            "ingredients": str_list,
            "directions": str(remaining_recipe.directions),
            "pdf_file": str(remaining_recipe.pdf_file)
        }

        return JsonResponse(data)


def grocery_list(request):
    # AJAX creates a grocery list from given lists of recipes and download it

    if request.method == "POST":
        string_array = request.body.decode("utf-8").split(",")

        srt_ingr = Recipe.objects.sort_recipe_ingredients(string_array)
        agg_ingr = RecipeIngredient.objects.aggregate_recipe_ingredients(srt_ingr)
        file = PDFHolder.objects.create_pdf(agg_ingr)

        response = HttpResponse(file, content_type='application/pdf')
        return response

recipes/templates/recipes/recipes_landing.html
{% extends 'faq/base.html' %}

{% block content %}

    <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Recettes</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Search form -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto" >
        <form action="{% url 'recipes:landing' %}" method="post">
          {% csrf_token %}
          <!-- <input type="hidden" class="hidden" value="question_id" name="question_id"> -->
            <div class="form-group {% if form.meal_number.errors %}has-warning has-feedback{% endif %}" >
              <label for="{{ form.meal_number.id_for_label }}" class="control-label">Combien de repas souhaitez vous préparer ?</label>
              {{ form.meal_number }}
            </div>
            <div class="form-group {% if form.course_options.errors %}has-warning has-feedback{% endif %}">
              <label for="{{ form.course_options.id_for_label }}" class="control-label">Quel(s) plat(s) doivent figurer au menu de chaque repas ?</label>
              {{ form.course_options }}
            </div>
            <button type="submit" name="action" value="question" class="btn btn-primary">C'est parti !</button>
        </form>
        {% if errors %}
          <div>
            {% for key, error in errors %}
            {% autoescape off %}
              {{ error }}
            {% endautoescape %}
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  <hr>

  {% if meal_list|length != 0 %}

  <!-- Search Result -->
  <div class="container">
    <div class="tab">
      {% for meal in meal_list %}
        <button class="tablinks" onclick="openMeal(event, 'Meal{{ forloop.counter }}')">Menu n°{{ forloop.counter }}</button>
      {% endfor %}
    </div>

      {% for meal in meal_list %}
      <div class="row meal-container" id="Meal{{ forloop.counter }}">
        {% for recipe in meal %}
          <div class="{% if meal|length == 1 %} col-lg-8
          {% elif meal|length == 2 %} col-lg-6
          {% else %} col-lg-4 mx-auto recipe-container
          {% endif %} mx-auto recipe-container"
          id="{{ recipe.type }}{{ recipe.id }}">
            <h3 class="text-center">{{ recipe.name }}</h3>
            <h5 class="text-center" style="color:#0085a1;">{{ recipe.get_type_display }}</h5>
            <h5>Ingrédients :</h5>
            <div>
              {% for ri in recipe.recipeingredient_set.all %}
                <p>{{ ri.ingredient.name }}{% if ri.quantity %} : {{ ri.quantity|floatformat }} {{ ri.unit }}{% endif %}</p>
              {% endfor %}
            </div>
            <h5>Instructions :</h5>
            <div>{{ recipe.directions|safe }}</div>
            <i class="fa fa-repeat">Trouver une autre recette</i>
            {% if recipe.pdf_file %}
            <p>
              <i class="fa fa-download" id="{{ recipe.pdf_file }}">
                <input type="hidden" name="variable" value="{{ recipe.id }}">
                Télécharger la recette
              </i>
            </p>
            {% endif %}
            <p>
              <input type="checkbox" id="{{ recipe.name }}">
              <label for="{{ recipe.name }}">Ajouter à la liste de courses</label>
            </p>
          </div>
        {% endfor %}
      </div>

      {% endfor %}

    <button type="submit" name="action" id="download-groceries-button" class="btn btn-primary col-lg-12">Télécharger la liste des courses</button>
    </div>


  {% endif %}

<script>
  var recipe_ids = ""
  {% for meal in meal_list %}
    {% for recipe in meal %}
      recipe_ids += "{{ recipe.id }} "
    {% endfor%}
  {% endfor %}
</script>

{% endblock %}