faq/urls.py
"""
This file contains the url paths for the faq app
"""


from django.urls import path

from faq import views

urlpatterns = [
    path(r'landing/', views.landing, name="landing"),
    path(r'memo_list/', views.memo_list, name="memo_list"),
    path(r'answer_search/', views.answer_search, name="answer_search"),
    path(r'answer_detail/<int:answer_id>', views.answer_detail, name="answer_detail"),
    path(r'answer_validate/', views.answer_validate, name="answer_validate"),
    path(r'question_ask/', views.question_ask, name="question_ask"),
    path(r'ml_info/', views.ml_info, name="ml_info"),
    ]

stradacore/urls.py
"""stradacore URL Configuration
contains the path for faq and recipes apps, admin,
and ckeditor library uploader
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static

from faq import views

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
    path('faq/', include(('faq.urls', 'faq'), namespace="faq")),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace="recipes")),
    path('videos/', include(('videos.urls', 'videos'), namespace="videos")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/models.py
"""
faq/models.py contains the Tag, Answer and Question models, and their managers
"""


from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from collections import Counter


class TagManager(models.Manager):
    # Manager for the tag model, contains the detect_tags method

    def detect_tags(self, string):
        """
        Takes an iterable of several strings,
        and returns a list of tags contained in those strings
        """
        detected_tags = []
        for tag in self.all():
            if tag.name.lower() in string.lower():
                detected_tags.append(tag)
        return detected_tags


class AnswerManager(models.Manager):
    # Manager for the answer model, contains the find_and_sort method
    def find_and_sort(self, iterable):
        """
        Find all answers matching an iterable of tags,
        and sort them from most to least relevant
        """
        found_list = []
        for tag in iterable:
            found_list.extend(self.filter(tags=tag))

        sorted_found_list = []
        for answer in Counter(found_list).most_common():
            sorted_found_list.append(answer[0])

        return sorted_found_list


class Tag(models.Model):
    # The Tag model is a simple charfield used to categorize the answers
    name = models.CharField(
        "mot",
        max_length=100,
        unique=True
    )
    objects = TagManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "mot-clé"
        verbose_name_plural = "mots-clé"
        indexes = [
            models.Index(fields=['name'], name='name_idx'),
        ]


class Answer(models.Model):
    """
    The Answer model is the core app functionality.
    It contains a title (string) and a content (using ck_editor upload field).
    Each answer is tagged with one or more tag.
    """

    title = models.CharField(
        "question posée",
        max_length=100,
        unique=True,
        default="Ex: 'Combien font deux et deux ?'"
    )
    upload_content = RichTextUploadingField(
        "réponse apportée",
        default="Ex: 'Deux et deux font quatre'",
        blank=True
    )
    tags = models.ManyToManyField(
        Tag,
        related_name="answers",
        blank=True,
        verbose_name="mots-clé"
    )
    objects = AnswerManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "réponse"
        verbose_name_plural = "réponses"


class Question(models.Model):
    """
    The Question model stores question asked by users, and possibly the
    asker's mail
    """
    content = models.TextField("question utilisateur")
    mail = models.EmailField("mail utilisateur", blank=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "question"
        verbose_name_plural = "questions"


class AnsweredQuestion(models.Model):
    """
    The Answered question model stores connection
    between user queries and relevant Answers
    """
    user_question = models.TextField()
    validated_answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

faq/forms.py
"""
Contains the faq app's forms, such as the question form,
used by the users to send a question to the admins.
"""

from django.forms import ModelForm, TextInput, EmailInput

from .models import Question


class QuestionForm(ModelForm):
    """
    The question form contains a required text field in which the user writes
    the question, and an optional email field where the user can write their
    mail address
    """

    class Meta:
        model = Question
        fields = ["content", "mail"]
        widget = {
            'content': TextInput(attrs={'class': 'form-control'}),
            'mail': EmailInput(attrs={'class': 'form-control'})
        }

faq/views.py
"""
The views of the faq app handle core features (such as index page)
as well as the search engine and detailed page of the Answers
"""

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from faq.forms import QuestionForm
from .models import Answer, Tag, AnsweredQuestion
from .utils import create_question

from unidecode import unidecode


def index(request):
    # Displays home page
    return render(request, 'faq/index.html')


def landing(request):
    # Displays faq app home page
    return render(request, 'faq/faq_landing.html')


def memo_list(request):
    # Displays a list of answers tagged as 'memo'
    answers = Answer.objects.filter(tags__name__icontains="memo")
    context = {
        'answers': answers
    }
    return render(request, 'faq/memo_list.html', context)


def answer_search(request):
    """
    Detects tags a in a user query
    and displays associated answers sorted by relevance
    """
    query = unidecode(request.GET.get('query'))
    request.session['last_query'] = query

    context = {
        'paginate': True,
        'form': QuestionForm(),
    }

    if not query:
        answer_list = Answer.objects.all()

    else:
        detected_tags = Tag.objects.detect_tags(query)
        answer_list = Answer.objects.find_and_sort(detected_tags)
        context['tags'] = detected_tags

    paginator = Paginator(answer_list, 7)
    page = request.GET.get('page')
    try:
        answers = paginator.page(page)
    except PageNotAnInteger:
        answers = paginator.page(1)
    except EmptyPage:
        answers = paginator.page(paginator.num_pages)

    context['answers'] = answers
    context['query'] = query

    return render(request, 'faq/answer_list.html', context)


def answer_detail(request, answer_id):
    """
    Displays the detailed content of an answer,
    specified through its primary key
    """
    answer = get_object_or_404(Answer, id=answer_id)
    form = QuestionForm()
    last_query = request.session.get('last_query', 'none')

    context = {
        "answer": answer,
        "form": form,
        "answer_id": answer_id,
        "last_query": last_query, }

    return render(request, 'faq/answer_detail.html', context)


def answer_validate(request):
    """
    Ajax view that creates an answered question
    from the current answer page and last user's query
    """
    if request.method == 'POST':
        user_question = request.POST.get("user_question")
        validated_answer = Answer.objects.get(pk=request.POST.get("answer_id"))
        AnsweredQuestion.objects.create(
            user_question=user_question,
            validated_answer=validated_answer
        )
        return HttpResponse('')


def question_ask(request):
    # Creates a Question object in db, using a Question Form
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            mail = form.cleaned_data['mail']
            create_question(content, mail)
            context = {
                'content': content,
                'mail': mail,
            }

            return render(request, 'faq/question_confirm.html', context)

        else:
            return redirect(request.META['HTTP_REFERER'])

    else:
        return redirect("faq:landing")


def ml_info(request):
    # Displays machine learning info page
    return render(request, 'faq/ml_info.html')

faq/templates/faq/answer_detail.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/post-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading text-center">
            <h1>{{ answer.title }}</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Answer Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-left">
         <p> {{ answer.upload_content|safe|urlize }} </p>
        </div>
      </div>
    </div>
  </article>

  <hr>

  <!-- Question Form -->
  <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-center">
          <button type="submit" class="btn btn-primary" id="satisfy">Cette réponse est utile !</button>
          <button type="submit" class="btn btn-primary" id="unsatisfy">Ça ne répond pas à ma question.</button>
          <p id="satisfied">Merci pour ce retour !</p>
        </div>
      </div>
  </div>

  <!-- Question Form -->
  <div class="container" id="unsatisfied">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-center">
          <h4 class="text-center question_tag">Aucune article ne semble répondre à votre question ?</h4>
        </div>
        <div class="col-lg-8 col-md-10 mx-auto text-left">
          <p style="margin-bottom: 20px;">Envoyez votre question en essayant d'être le plus spécifique possible. Vous pouvez préciser votre adresse mail pour être notifié.e dès que la réponse sera en ligne.</p>
        </div>
      </div>

    {% include "faq/question_form.html" %}
  </div>

  <hr>

<script>
   var answer_id = {{ answer_id }};
   var last_query = "{{ last_query }}";
</script>

{% endblock %}

faq/templates/faq/answer_list.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ list_title }}</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row" style="margin-bottom: 20px;" >
     {% include 'faq/search_form.html' %}
    </div>
  </div>
    {% if answers|length_is:"0" %}
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto text-center">
            <h4 class="text-center question_tag">Aucune réponse ne correspond à votre question. Essayez de nouveau en changeant les termes employés.</h4>
          </div>
        </div>
      </div>

    {% else %}
    <div class="container">
      <div class="row">
        <!-- Answers -->
        <div class="col-lg-8 col-md-10 mx-auto">

            {% for answer in answers %}

              <div class="post-preview">
                <a href="{% url 'faq:answer_detail' answer_id=answer.id %}">
                  <h2 class="post-title">
                      {{ answer.title }}
                  </h2>
                  <p class="post-subtitle">
                    {{ answer.upload_content|slice:":400"|safe }}
                  </p>
                </a>
              </div>

            {% endfor %}

            {% if paginate %}

              <!-- Pager -->
              <div class="clearfix">
                <ul class="pager">
                  {% if answers.has_previous %}
                      <li><a href="?query={{ query }}&page={{ answers.previous_page_number }}" class="btn btn-primary float-left">&larr; Réponses précédentes</a></li>
                  {% endif %}
                  {% if answers.has_next %}
                      <li><a href="?query={{ query }}&page={{ answers.next_page_number }}" class="btn btn-primary float-right">Réponses suivantes &rarr;</a></li>
                  {% endif %}
                </ul>
              </div>

            {% endif %}

        </div>

        <!-- Tags -->
        <div class="col-lg-2 col-md-2 mx-auto side-tags">
          <h3>Mots-clé</h3>
          {% for tag in tags %}
          <a href="/faq/answer_search/?query={{ tag.name }}">
            <p>{{ tag.name }}</p>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %}


    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8 mx-auto">
          <p style="margin-bottom: 20px;">Vous pouvez également envoyer votre question en détail directement au service. Vous pouvez préciser votre adresse mail pour être notifié.e dès que la réponse sera en ligne.</p>
        </div>
      </div>
      {% include "faq/question_form.html" %}
    </div>

  <hr>
{% endblock %}

faq/templates/faq/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>A Strada di u Core</title>

  {% load static %}

  <link href="{% static 'faq/img/favicon.png' %}" rel="icon" type="image/png">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'faq/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'faq/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'faq/css/clean-blog.min.css' %}" rel="stylesheet">
  <link href="{% static 'faq/css/clean-blog-custom.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/">Bienvenue</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:landing' %}">Questions & Réponses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:memo_list' %}">Mémos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:landing' %}">Recettes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:landing' %}">Vidéos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:ml_info' %}">Infos techniques</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% block content %}{% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Copyright &copy; Victor Sorba pour A Strada di u Core 2019</p>
        </div>
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Theme : Clean Blog, available on <a href="https://startbootstrap.com/">Start Bootstrap</a></p>
        </div>
        <div class="col-lg-12 col-md-12 mx-auto text-center">
          <img src="{% static 'faq/img/logo_ssr.jpg' %}" />
          <img src="{% static 'faq/img/logo_ireps.png' %}" />
          <img src="{% static 'faq/img/logo_pramca.jpg' %}" />
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'faq/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'faq/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'faq/js/clean-blog.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
  <script src="{% static 'faq/js/clean-blog-custom.js' %}"></script>

</body>

</html>

faq/templates/faq/faq_landing.html
{% extends 'faq/base.html' %}

{% block content %}

    <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Questions & Réponses</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
    {% include 'faq/search_form.html' %}
    </div>
  </div>

{% endblock %}

faq/templates/faq/index.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'faq/img/about-bg.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>A Strada di u Core</h1>
          <span class="subheading">Questions & recettes !</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>L'association A Strada di u Core met à votre disposition deux services pour prendre soin de votre santé.</p>
      <p>Des questions sur un sujet de cardiologie ? <a href="{% url 'faq:landing' %}">Retrouvez ici</a> de nombreuses réponses élaborées par l'équipe du centre.</p>
      <p>En panne d'inspiration pour vos repas cette semaine ? <a href="{% url 'recipes:landing' %}">Les recettes du centre</a> vous proposent des menus personnalisés, simples et équilibrés.</p>
      <p>Ce site utilise des technologies de machine learning ! Pour en savoir plus, consultez <a href="{% url 'faq:ml_info' %}">cette page</a> !</p>
    </div>
  </div>
</div>

<hr>

{% endblock %}

faq/templates/faq/list.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{ list_title }}</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row" style="margin-bottom: 20px;" >
     {% include 'faq/search_form.html' %}
    </div>
  </div>
    {% if answers|length_is:"0" %}
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto text-center">
            <h4 class="text-center question_tag">Aucune réponse ne correspond à votre question. Essayez de nouveau, en changeant les termes employés.</h4>
          </div>
          <div class="col-lg-8 col-md-10 mx-auto text-left">
            <p style="margin-bottom: 20px;">Vous pouvez également envoyer votre question en détail directement au service. Vous pouvez préciser votre adresse mail pour être notifié.e dès que la réponse sera en ligne.</p>
          </div>
        </div>
        {% include "faq/question_form.html" %}
      </div>

    {% else %}
    <div class="container">
      <div class="row">
        <!-- Answers -->
        <div class="col-lg-8 col-md-10 mx-auto">

            {% for answer in answers %}

              <div class="post-preview">
                <a href="{% url 'faq:answer_detail' answer_id=answer.id %}">
                  <h2 class="post-title">
                      {{ answer.title }}
                  </h2>
                  <p class="post-subtitle">
                    {{ answer.upload_content|slice:":400"|safe }}
                  </p>
                </a>
              </div>
              <hr>

            {% endfor %}

            {% if paginate %}

              <!-- Pager -->
              <div class="clearfix">
                <ul class="pager">
                  {% if answers.has_previous %}
                      <li><a href="?query={{ query }}&page={{ answers.previous_page_number }}" class="btn btn-primary float-left">&larr; Réponses précédentes</a></li>
                  {% endif %}
                  {% if answers.has_next %}
                      <li><a href="?query={{ query }}&page={{ answers.next_page_number }}" class="btn btn-primary float-right">Réponses suivantes &rarr;</a></li>
                  {% endif %}
                </ul>
              </div>

            {% endif %}

        </div>

        <!-- Tags -->
        <div class="col-lg-2 col-md-2 mx-auto side-tags">
          <h3>Mots-clé</h3>
          {% for tag in tags %}
          <a href="/faq/answer_search/?query={{ tag.name }}">
            <p>{{ tag.name }}</p>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %}

  <hr>
{% endblock %}

faq/templates/faq/list_answer.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

    {% include 'faq/list.html' with list_title='Résultats de votre recherche' %}

{% endblock %}

faq/templates/faq/list_memo.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Mémos</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
        {% include 'faq/search_form.html' %}
    </div>

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            {% for answer in answers %}

              <div class="post-preview">
                <a href="{% url 'faq:answer_detail' answer_id=answer.id %}">
                  <h2 class="post-title">
                      {{ answer.title }}
                  </h2>
                </a>
              </div>
              <hr>

            {% endfor %}

            {% if paginate %}

              <!-- Pager -->
              <div class="clearfix">
                <ul class="pager">
                {% if questions.has_next %}
                    <li><a href="?page={{ questions.next_page_number }}" class="btn btn-primary float-right">Réponses suivantes &rarr;</a></li>
                {% endif %}
                {% if questions.has_previous %}
                    <li><a href="?page={{ questions.previous_page_number }}" class="btn btn-primary float-left">Réponses précédentes &larr;</a></li>
                {% endif %}
                </ul>
              </div>

            {% endif %}

        </div>
      </div>
  </div>

  <hr>

{% endblock %}

faq/templates/faq/memo_list.html
{% extends 'faq/base.html' %}

{% load static %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Mémos</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
        {% include 'faq/search_form.html' %}
    </div>

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            {% for answer in answers %}

              <div class="post-preview">
                <a href="{% url 'faq:answer_detail' answer_id=answer.id %}">
                  <h2 class="post-title">
                      {{ answer.title }}
                  </h2>
                </a>
              </div>
              <hr>

            {% endfor %}

            {% if paginate %}

              <!-- Pager -->
              <div class="clearfix">
                <ul class="pager">
                {% if questions.has_next %}
                    <li><a href="?page={{ questions.next_page_number }}" class="btn btn-primary float-right">Réponses suivantes &rarr;</a></li>
                {% endif %}
                {% if questions.has_previous %}
                    <li><a href="?page={{ questions.previous_page_number }}" class="btn btn-primary float-left">Réponses précédentes &larr;</a></li>
                {% endif %}
                </ul>
              </div>

            {% endif %}

        </div>
      </div>
  </div>

  <hr>

{% endblock %}

faq/templates/faq/question_confirm.html
{% extends 'faq/base.html' %}

{% block content %}
<header class="masthead" style="background-image: url('faq/img/about-none.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>Votre demande a bien été prise en compte</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      Votre question <em>"{{content}}"</em> a été enregistrée et sera traitée sous peu.
      {% if mail %}Une fois la réponse mise en ligne, un mail de notification sera envoyé à l'adresse {{mail}}.{% endif %}
      <a href="{% url 'faq:landing' %}">Retour à l'accueil</a>
    </div>
  </div>
</div>

<hr>

{% endblock %}

faq/templates/faq/question_form.html
<div class="row">
  <div class="col-lg-8 col-md-10 mx-auto" >
    <form action="{% url 'faq:question_ask' %}" method="post">
      {% csrf_token %}
      <!-- <input type="hidden" class="hidden" value="question_id" name="question_id"> -->
        <div class="form-group {% if form.content.errors %}has-warning has-feedback{% endif %}" >
          <label for="{{ form.content.id_for_label }}" class="control-label">Votre question</label>
        </div>
        <div>
          {{ form.content }}
        </div>
        <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
          <label for="{{ form.mail.id_for_label }}" class="control-label">Votre adresse email <em>(facultatif)</em></label>
          {{ form.mail }}
        </div>
        <button type="submit" name="action" value="question" class="btn btn-success">Envoyer</button>
    </form>
    {% if errors %}
      <div>
        {% for key, error in errors %}
        {% autoescape off %}
          {{ error }}
        {% endautoescape %}
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>

faq/templates/faq/search_form.html
<div class="col-lg-12 detail-separator">
  <form class="col-md-12 text-center" action="{% url 'faq:answer_search' %}" method="get" accept-charset="utf-8">
    <div class="form-group">
      <label for="searchForm">Posez votre question</label>
      <input id="searchForm" class="form-control" name="query">
    </div>
    <span class="help-block" id="helpBlock">Affinez la pertinence de la recherche en précisant le plus de détails possible</span>
  </form>
</div>